-- EP1-ST035: fifth reviewed vocabulary batch for the Phase 1 learner beta.
-- All rows are EnglishPath-authored CC0 fixtures. Rollback is owner-approved only.

INSERT INTO "GovernedVocabularyItem" ("id", "taxonomyNodeId", "word", "meaning", "example", "pronunciation", "source", "license", "reviewStatus", "reviewedAt", "publishStatus", "publishedAt", "updatedAt")
SELECT batch."id", batch."taxonomyNodeId", batch."word", batch."meaning", batch."example", NULL,
  'EnglishPath original batch 5 ' || batch."id", 'CC0-1.0', 'REVIEWED', TIMESTAMPTZ '2026-08-06T00:00:00Z',
  'PUBLISHED', TIMESTAMPTZ '2026-08-06T00:00:00Z', TIMESTAMPTZ '2026-08-06T00:00:00Z'
FROM (VALUES
  ('vocab-b5-001', 'daily-life-travel', 'across', 'băng qua', 'We walked across the square.'),
  ('vocab-b5-002', 'daily-life-travel', 'footpath', 'lối đi bộ', 'The footpath follows the river.'),
  ('vocab-b5-003', 'daily-life-travel', 'forest', 'rừng', 'The forest trail is open today.'),
  ('vocab-b5-004', 'daily-life-travel', 'museum', 'bảo tàng', 'The museum opens at nine.'),
  ('vocab-b5-005', 'daily-life-travel', 'ocean', 'đại dương', 'The hotel faces the ocean.'),
  ('vocab-b5-006', 'daily-life-travel', 'overnight', 'qua đêm', 'We made an overnight stop in Hanoi.'),
  ('vocab-b5-007', 'daily-life-travel', 'rail', 'đường ray', 'The rail line passes through the valley.'),
  ('vocab-b5-008', 'daily-life-travel', 'sea', 'biển', 'The sea was calm in the morning.'),
  ('vocab-b5-009', 'daily-life-travel', 'south', 'phía nam', 'The bus travels south after lunch.'),
  ('vocab-b5-010', 'daily-life-travel', 'stay', 'lưu trú', 'Our stay lasted three nights.'),
  ('vocab-b5-011', 'daily-life-travel', 'street', 'đường phố', 'The street is closed for the festival.'),
  ('vocab-b5-012', 'daily-life-travel', 'taxi', 'taxi', 'A taxi took us to the hotel.'),
  ('vocab-b5-013', 'daily-life-travel', 'town', 'thị trấn', 'The town has a friendly market.'),
  ('vocab-b5-014', 'daily-life-travel', 'transport', 'phương tiện giao thông', 'Public transport is convenient here.'),
  ('vocab-b5-015', 'daily-life-travel', 'valley', 'thung lũng', 'The valley is green after the rain.'),
  ('vocab-b5-016', 'daily-life-travel', 'village', 'ngôi làng', 'The village is beside the river.'),
  ('vocab-b5-017', 'daily-life-travel', 'zone', 'khu vực', 'The station has a quiet waiting zone.'),
  ('vocab-b5-018', 'daily-life-travel', 'arrival-hall', 'sảnh đến', 'Meet me in the arrival-hall.'),
  ('vocab-b5-019', 'daily-life-travel', 'avenue', 'đại lộ', 'The avenue leads to the park.'),
  ('vocab-b5-020', 'daily-life-travel', 'canal', 'kênh đào', 'Boats travel along the canal.'),
  ('vocab-b5-021', 'daily-life-travel', 'check-in', 'làm thủ tục nhận phòng', 'Check-in begins at two o clock.'),
  ('vocab-b5-022', 'daily-life-travel', 'coastal', 'ven biển', 'The coastal road has great views.'),
  ('vocab-b5-023', 'daily-life-travel', 'crowded', 'đông đúc', 'The market is crowded at noon.'),
  ('vocab-b5-024', 'daily-life-travel', 'direction-sign', 'biển chỉ hướng', 'Follow the direction-sign to the exit.'),
  ('vocab-b5-025', 'daily-life-travel', 'entrance-fee', 'phí vào cửa', 'The entrance-fee supports the museum.'),
  ('vocab-b5-026', 'daily-life-travel', 'guidebook', 'sách hướng dẫn', 'The guidebook lists local restaurants.'),
  ('vocab-b5-027', 'daily-life-travel', 'inquiry-desk', 'quầy hỏi đáp', 'The inquiry-desk is near the entrance.'),
  ('vocab-b5-028', 'daily-life-travel', 'outdoor', 'ngoài trời', 'The hotel has an outdoor pool.'),
  ('vocab-b5-029', 'daily-life-travel', 'scenic', 'có phong cảnh đẹp', 'The train takes a scenic route.'),
  ('vocab-b5-030', 'daily-life-travel', 'travelling', 'việc đi du lịch', 'Travelling teaches us about other cultures.'),
  ('vocab-b5-031', 'professional-technology', 'accessibility', 'khả năng tiếp cận', 'Accessibility helps every learner use the page.'),
  ('vocab-b5-032', 'professional-technology', 'actor', 'tác nhân', 'The actor is recorded in the audit event.'),
  ('vocab-b5-033', 'professional-technology', 'api-key', 'khóa API', 'An API-key must stay outside the browser.'),
  ('vocab-b5-034', 'professional-technology', 'assert', 'khẳng định', 'The test can assert the exact count.'),
  ('vocab-b5-035', 'professional-technology', 'backend', 'phía máy chủ', 'The backend owns the publication rule.'),
  ('vocab-b5-036', 'professional-technology', 'checksum', 'mã kiểm tra', 'The checksum identifies the source version.'),
  ('vocab-b5-037', 'professional-technology', 'credential', 'thông tin xác thực', 'A credential must never enter a fixture.'),
  ('vocab-b5-038', 'professional-technology', 'diff', 'phần khác biệt', 'Review the diff before committing.'),
  ('vocab-b5-039', 'professional-technology', 'encoding', 'mã hóa ký tự', 'The file uses UTF encoding.'),
  ('vocab-b5-040', 'professional-technology', 'hash', 'mã băm', 'The hash changes when the source changes.'),
  ('vocab-b5-041', 'professional-technology', 'header', 'tiêu đề HTTP', 'The header carries the correlation ID.'),
  ('vocab-b5-042', 'professional-technology', 'integration', 'tích hợp', 'The integration test uses local boundaries.'),
  ('vocab-b5-043', 'professional-technology', 'lock', 'khóa', 'The loop lock prevents competing runs.'),
  ('vocab-b5-044', 'professional-technology', 'mock', 'mô phỏng', 'The test uses a mock identity provider.'),
  ('vocab-b5-045', 'professional-technology', 'observability', 'khả năng quan sát', 'Observability helps find slow requests.'),
  ('vocab-b5-046', 'professional-technology', 'openapi', 'chuẩn OpenAPI', 'The OpenAPI document describes the endpoint.'),
  ('vocab-b5-047', 'professional-technology', 'parse', 'phân tích cú pháp', 'The client parses only known fields.'),
  ('vocab-b5-048', 'professional-technology', 'snapshot', 'ảnh chụp trạng thái', 'The snapshot keeps a deterministic fixture.'),
  ('vocab-b5-049', 'professional-technology', 'throttle', 'giới hạn tốc độ', 'The server can throttle repeated requests.'),
  ('vocab-b5-050', 'professional-technology', 'warning', 'cảnh báo', 'The build shows a warning for old syntax.'),
  ('vocab-b5-051', 'professional-technology', 'whitespace', 'khoảng trắng', 'The formatter removes extra whitespace.'),
  ('vocab-b5-052', 'professional-technology', 'worker', 'tiến trình xử lý', 'The worker processes one bounded job.'),
  ('vocab-b5-053', 'professional-technology', 'workspace', 'không gian làm việc', 'The workspace starts from a clean branch.'),
  ('vocab-b5-054', 'professional-technology', 'xss', 'tấn công chèn mã', 'The renderer protects against XSS.'),
  ('vocab-b5-055', 'professional-technology', 'yaml', 'định dạng YAML', 'The status file is valid YAML.'),
  ('vocab-b5-056', 'professional-technology', 'zero-downtime', 'không gián đoạn', 'The planned update aims for zero-downtime.'),
  ('vocab-b5-057', 'professional-technology', 'artifact', 'tạo phẩm', 'The plan artifact is stored for review.'),
  ('vocab-b5-058', 'professional-technology', 'backoff', 'thời gian chờ tăng dần', 'Retry uses a short backoff.'),
  ('vocab-b5-059', 'professional-technology', 'correlation', 'tương quan', 'The correlation links the request logs.'),
  ('vocab-b5-060', 'professional-technology', 'deprecation', 'ngừng hỗ trợ', 'The notice explains the deprecation.'),
  ('vocab-b5-061', 'professional-technology', 'exposure', 'sự phơi lộ', 'The review checks for secret exposure.'),
  ('vocab-b5-062', 'professional-technology', 'fallback', 'phương án dự phòng', 'The client shows a safe fallback.'),
  ('vocab-b5-063', 'professional-technology', 'generation', 'sự tạo sinh', 'Code generation follows the schema.'),
  ('vocab-b5-064', 'professional-technology', 'heartbeat', 'tín hiệu sống', 'The worker sends a heartbeat.'),
  ('vocab-b5-065', 'professional-technology', 'incremental', 'tăng dần', 'The migration is incremental and additive.'),
  ('vocab-b5-066', 'professional-technology', 'join', 'kết hợp', 'The query can join related records.'),
  ('vocab-b5-067', 'professional-technology', 'key', 'khóa định danh', 'The key identifies one request.'),
  ('vocab-b5-068', 'professional-technology', 'logging-level', 'mức ghi nhật ký', 'The logging-level stays bounded in production.'),
  ('vocab-b5-069', 'professional-technology', 'origin', 'nguồn gốc', 'The browser checks the request origin.'),
  ('vocab-b5-070', 'professional-technology', 'sandbox', 'môi trường cô lập', 'The test runs in a local sandbox.'),
  ('vocab-b5-071', 'workplace-meetings', 'achievement', 'thành tích', 'The learner celebrates each achievement.'),
  ('vocab-b5-072', 'workplace-meetings', 'address', 'địa chỉ', 'Please check the delivery address.'),
  ('vocab-b5-073', 'workplace-meetings', 'agreement', 'thỏa thuận', 'Both teams signed the agreement.'),
  ('vocab-b5-074', 'workplace-meetings', 'appointment', 'cuộc hẹn', 'The appointment is at ten.'),
  ('vocab-b5-075', 'workplace-meetings', 'assistant', 'trợ lý', 'The assistant prepared the room.'),
  ('vocab-b5-076', 'workplace-meetings', 'cooperation', 'sự hợp tác', 'The project depends on cooperation.'),
  ('vocab-b5-077', 'workplace-meetings', 'email', 'thư điện tử', 'Send the details by email.'),
  ('vocab-b5-078', 'workplace-meetings', 'leader', 'người lãnh đạo', 'The leader thanked the team.'),
  ('vocab-b5-079', 'workplace-meetings', 'location', 'địa điểm', 'The location is easy to reach.'),
  ('vocab-b5-080', 'workplace-meetings', 'message', 'tin nhắn', 'I received your message.'),
  ('vocab-b5-081', 'workplace-meetings', 'notice', 'thông báo', 'The notice explains the schedule change.'),
  ('vocab-b5-082', 'workplace-meetings', 'offer', 'lời đề nghị', 'The company made a fair offer.'),
  ('vocab-b5-083', 'workplace-meetings', 'organization', 'tổ chức', 'The organization supports free learning.'),
  ('vocab-b5-084', 'workplace-meetings', 'presentation', 'bài thuyết trình', 'Her presentation was clear and brief.'),
  ('vocab-b5-085', 'workplace-meetings', 'professional', 'chuyên nghiệp', 'He gave a professional response.'),
  ('vocab-b5-086', 'workplace-meetings', 'qualification', 'bằng cấp', 'The role requires one qualification.'),
  ('vocab-b5-087', 'workplace-meetings', 'recommend', 'giới thiệu', 'I recommend this short course.'),
  ('vocab-b5-088', 'workplace-meetings', 'reference', 'tài liệu tham khảo', 'The guide is a useful reference.'),
  ('vocab-b5-089', 'workplace-meetings', 'responsible', 'chịu trách nhiệm', 'Who is responsible for the update?'),
  ('vocab-b5-090', 'workplace-meetings', 'retail', 'bán lẻ', 'She works in retail during the weekend.'),
  ('vocab-b5-091', 'workplace-meetings', 'sign', 'ký', 'Please sign the attendance sheet.'),
  ('vocab-b5-092', 'workplace-meetings', 'supervisor', 'người giám sát', 'The supervisor checked the plan.'),
  ('vocab-b5-093', 'workplace-meetings', 'approval', 'sự phê duyệt', 'The change needs owner approval.'),
  ('vocab-b5-094', 'workplace-meetings', 'document', 'tài liệu', 'The document lists the requirements.'),
  ('vocab-b5-095', 'workplace-meetings', 'executive', 'lãnh đạo cấp cao', 'The executive joined the review.'),
  ('vocab-b5-096', 'workplace-meetings', 'finance', 'tài chính', 'Finance checked the invoice.'),
  ('vocab-b5-097', 'workplace-meetings', 'hire', 'tuyển dụng', 'The company plans to hire two teachers.'),
  ('vocab-b5-098', 'workplace-meetings', 'quarter', 'quý', 'The report covers the last quarter.'),
  ('vocab-b5-099', 'workplace-meetings', 'record', 'bản ghi', 'The record contains the final result.'),
  ('vocab-b5-100', 'workplace-meetings', 'standard', 'tiêu chuẩn', 'The standard keeps content quality consistent.')
) AS batch("id", "taxonomyNodeId", "word", "meaning", "example");
