-- EP1-ST032: second reviewed vocabulary batch for the Phase 1 learner beta.
-- All rows are EnglishPath-authored CC0 fixtures. Rollback is owner-approved only:
-- remove rows whose IDs start with vocab-b2- if a governed data decision requires it.

INSERT INTO "GovernedVocabularyItem" ("id", "taxonomyNodeId", "word", "meaning", "example", "pronunciation", "source", "license", "reviewStatus", "reviewedAt", "publishStatus", "publishedAt", "updatedAt")
SELECT batch."id", batch."taxonomyNodeId", batch."word", batch."meaning", batch."example", batch."pronunciation",
  'EnglishPath original batch 2 ' || batch."id", 'CC0-1.0', 'REVIEWED', TIMESTAMPTZ '2026-08-06T00:00:00Z',
  'PUBLISHED', TIMESTAMPTZ '2026-08-06T00:00:00Z', TIMESTAMPTZ '2026-08-06T00:00:00Z'
FROM (VALUES
  ('vocab-b2-001', 'daily-life-travel', 'airport', 'sân bay', 'The airport is thirty minutes from the city.', '/ˈeəpɔːt/'),
  ('vocab-b2-002', 'daily-life-travel', 'aisle', 'lối đi giữa các hàng ghế', 'Please keep the aisle clear.', '/aɪl/'),
  ('vocab-b2-003', 'daily-life-travel', 'boarding', 'việc lên máy bay', 'Boarding starts at gate seven.', '/ˈbɔːdɪŋ/'),
  ('vocab-b2-004', 'daily-life-travel', 'cabin', 'khoang hành khách', 'The cabin was quiet during the flight.', '/ˈkæbɪn/'),
  ('vocab-b2-005', 'daily-life-travel', 'carriage', 'toa tàu', 'Our seats are in the second carriage.', '/ˈkærɪdʒ/'),
  ('vocab-b2-006', 'daily-life-travel', 'conductor', 'nhân viên soát vé', 'The conductor checked our tickets.', '/kənˈdʌktə/'),
  ('vocab-b2-007', 'daily-life-travel', 'currency', 'tiền tệ', 'The local currency is easy to exchange.', '/ˈkʌrənsi/'),
  ('vocab-b2-008', 'daily-life-travel', 'domestic', 'nội địa', 'The airline operates domestic flights.', '/dəˈmestɪk/'),
  ('vocab-b2-009', 'daily-life-travel', 'embassy', 'đại sứ quán', 'The embassy can help replace a lost passport.', '/ˈembəsi/'),
  ('vocab-b2-010', 'daily-life-travel', 'entrance', 'lối vào', 'The museum entrance is on the main street.', '/ˈentrəns/'),
  ('vocab-b2-011', 'daily-life-travel', 'exchange', 'đổi tiền', 'We need to exchange some money before dinner.', '/ɪksˈtʃeɪndʒ/'),
  ('vocab-b2-012', 'daily-life-travel', 'gate', 'cổng lên máy bay', 'The screen shows our gate number.', '/ɡeɪt/'),
  ('vocab-b2-013', 'daily-life-travel', 'hostel', 'nhà nghỉ', 'The hostel offers a simple breakfast.', '/ˈhɒstəl/'),
  ('vocab-b2-014', 'daily-life-travel', 'immigration', 'nhập cảnh', 'The immigration line moved quickly.', '/ˌɪmɪˈɡreɪʃən/'),
  ('vocab-b2-015', 'daily-life-travel', 'journey', 'hành trình', 'The journey from Hue took four hours.', '/ˈdʒɜːni/'),
  ('vocab-b2-016', 'daily-life-travel', 'landmark', 'địa danh', 'The bridge is a famous city landmark.', '/ˈlændmɑːk/'),
  ('vocab-b2-017', 'daily-life-travel', 'lounge', 'phòng chờ', 'We waited in the airport lounge.', '/laʊndʒ/'),
  ('vocab-b2-018', 'daily-life-travel', 'overseas', 'ở nước ngoài', 'She hopes to study overseas next year.', '/ˌəʊvəˈsiːz/'),
  ('vocab-b2-019', 'daily-life-travel', 'passenger', 'hành khách', 'Every passenger must show a ticket.', '/ˈpæsɪndʒə/'),
  ('vocab-b2-020', 'daily-life-travel', 'railway', 'đường sắt', 'The railway connects several coastal towns.', '/ˈreɪlweɪ/'),
  ('vocab-b2-021', 'daily-life-travel', 'receipt', 'biên lai', 'Keep the receipt for your hotel payment.', '/rɪˈsiːt/'),
  ('vocab-b2-022', 'daily-life-travel', 'reception', 'quầy lễ tân', 'Ask reception for a spare key.', '/rɪˈsepʃən/'),
  ('vocab-b2-023', 'daily-life-travel', 'resort', 'khu nghỉ dưỡng', 'The resort has a small swimming pool.', '/rɪˈzɔːt/'),
  ('vocab-b2-024', 'daily-life-travel', 'souvenir', 'quà lưu niệm', 'I bought a small souvenir for my sister.', '/ˌsuːvəˈnɪə/'),
  ('vocab-b2-025', 'daily-life-travel', 'terminal', 'nhà ga cuối', 'The bus leaves from the north terminal.', '/ˈtɜːmɪnəl/'),
  ('vocab-b2-026', 'daily-life-travel', 'tourist', 'khách du lịch', 'The guide answered the tourist question.', '/ˈtʊərɪst/'),
  ('vocab-b2-027', 'daily-life-travel', 'traffic', 'giao thông', 'Heavy traffic made us late.', '/ˈtræfɪk/'),
  ('vocab-b2-028', 'daily-life-travel', 'transit', 'quá cảnh', 'We have a short transit in Singapore.', '/ˈtrænzɪt/'),
  ('vocab-b2-029', 'daily-life-travel', 'visa', 'thị thực', 'Check the visa rules before booking a flight.', '/ˈviːzə/'),
  ('vocab-b2-030', 'daily-life-travel', 'voyage', 'chuyến đi dài', 'The sea voyage lasted three days.', '/ˈvɔɪɪdʒ/'),
  ('vocab-b2-031', 'daily-life-travel', 'window', 'cửa sổ', 'I chose a window seat for the flight.', '/ˈwɪndəʊ/'),
  ('vocab-b2-032', 'daily-life-travel', 'accompany', 'đi cùng', 'Can you accompany me to the station?', '/əˈkʌmpəni/'),
  ('vocab-b2-033', 'daily-life-travel', 'adventure', 'cuộc phiêu lưu', 'The island trip was a memorable adventure.', '/ədˈventʃə/'),
  ('vocab-b2-034', 'daily-life-travel', 'landing', 'sự hạ cánh', 'Our landing is expected before noon.', '/ˈlændɪŋ/'),
  ('vocab-b2-035', 'daily-life-travel', 'backpack', 'ba lô', 'My backpack fits under the seat.', '/ˈbækpæk/'),
  ('vocab-b2-036', 'daily-life-travel', 'brochure', 'tờ giới thiệu', 'The hotel brochure lists local tours.', '/ˈbrəʊʃə/'),
  ('vocab-b2-037', 'daily-life-travel', 'coast', 'bờ biển', 'We walked along the coast at sunset.', '/kəʊst/'),
  ('vocab-b2-038', 'daily-life-travel', 'outbound', 'hướng đi ra', 'The outbound train leaves at six.', '/ˈaʊtbaʊnd/'),
  ('vocab-b2-039', 'daily-life-travel', 'explore', 'khám phá', 'We plan to explore the old quarter.', '/ɪkˈsplɔː/'),
  ('vocab-b2-040', 'daily-life-travel', 'southern', 'phía nam', 'The southern route is usually warmer.', '/ˈsʌðən/'),
  ('vocab-b2-041', 'professional-technology', 'application', 'ứng dụng', 'The application saves each completed lesson.', '/ˌæplɪˈkeɪʃən/'),
  ('vocab-b2-042', 'professional-technology', 'architecture', 'kiến trúc hệ thống', 'The architecture separates the API and web app.', '/ˈɑːkɪtektʃə/'),
  ('vocab-b2-043', 'professional-technology', 'bandwidth', 'băng thông', 'Video needs more bandwidth than text.', '/ˈbændwɪdθ/'),
  ('vocab-b2-044', 'professional-technology', 'command', 'lệnh', 'Run the command from the project folder.', '/kəˈmɑːnd/'),
  ('vocab-b2-045', 'professional-technology', 'component', 'thành phần', 'The component displays a loading state.', '/kəmˈpəʊnənt/'),
  ('vocab-b2-046', 'professional-technology', 'configuration', 'cấu hình', 'The configuration keeps local ports predictable.', '/kənˌfɪɡəˈreɪʃən/'),
  ('vocab-b2-047', 'professional-technology', 'connection', 'kết nối', 'The connection closed after the response.', '/kəˈnekʃən/'),
  ('vocab-b2-048', 'professional-technology', 'console', 'bảng điều khiển', 'The browser console shows no application error.', '/kənˈsəʊl/'),
  ('vocab-b2-049', 'professional-technology', 'container', 'vùng chứa', 'The service runs inside a secure container.', '/kənˈteɪnə/'),
  ('vocab-b2-050', 'professional-technology', 'dashboard', 'bảng điều khiển tổng quan', 'The dashboard summarizes learner progress.', '/ˈdæʃbɔːd/'),
  ('vocab-b2-051', 'professional-technology', 'directory', 'thư mục', 'The migration file is in the directory.', '/dəˈrektəri/'),
  ('vocab-b2-052', 'professional-technology', 'domain', 'miền', 'The domain identifies the learning area.', '/dəˈmeɪn/'),
  ('vocab-b2-053', 'professional-technology', 'driver', 'trình điều khiển', 'The database driver opens a safe connection.', '/ˈdraɪvə/'),
  ('vocab-b2-054', 'professional-technology', 'encryption', 'mã hóa', 'Encryption protects data while it travels.', '/ɪnˈkrɪpʃən/'),
  ('vocab-b2-055', 'professional-technology', 'error', 'lỗi', 'The service returns a safe error message.', '/ˈerə/'),
  ('vocab-b2-056', 'professional-technology', 'format', 'định dạng', 'The response follows the approved format.', '/ˈfɔːmæt/'),
  ('vocab-b2-057', 'professional-technology', 'function', 'hàm', 'This function validates the input.', '/ˈfʌŋkʃən/'),
  ('vocab-b2-058', 'professional-technology', 'hardware', 'phần cứng', 'The hardware needs a regular check.', '/ˈhɑːdweə/'),
  ('vocab-b2-059', 'professional-technology', 'host', 'máy chủ lưu trữ', 'The host serves the local application.', '/həʊst/'),
  ('vocab-b2-060', 'professional-technology', 'import', 'nhập', 'The system can import a reviewed file.', '/ɪmˈpɔːt/'),
  ('vocab-b2-061', 'professional-technology', 'index', 'chỉ mục', 'The index makes the lookup faster.', '/ˈɪndeks/'),
  ('vocab-b2-062', 'professional-technology', 'input', 'dữ liệu nhập', 'The form rejects empty input.', '/ˈɪnpʊt/'),
  ('vocab-b2-063', 'professional-technology', 'library', 'thư viện', 'The library provides a tested helper.', '/ˈlaɪbrəri/'),
  ('vocab-b2-064', 'professional-technology', 'module', 'mô đun', 'Each module owns one bounded responsibility.', '/ˈmɒdjuːl/'),
  ('vocab-b2-065', 'professional-technology', 'monitor', 'giám sát', 'The monitor alerts the team to failures.', '/ˈmɒnɪtə/'),
  ('vocab-b2-066', 'professional-technology', 'output', 'kết quả đầu ra', 'The command prints its output clearly.', '/ˈaʊtpʊt/'),
  ('vocab-b2-067', 'professional-technology', 'password', 'mật khẩu', 'Never place a password in a log.', '/ˈpɑːswɜːd/'),
  ('vocab-b2-068', 'professional-technology', 'plugin', 'tiện ích mở rộng', 'The plugin adds a small editor tool.', '/ˈplʌɡɪn/'),
  ('vocab-b2-069', 'professional-technology', 'protocol', 'giao thức', 'The API follows a documented protocol.', '/ˈprəʊtəkɒl/'),
  ('vocab-b2-070', 'professional-technology', 'query', 'truy vấn', 'The query requests one page of items.', '/ˈkwɪəri/'),
  ('vocab-b2-071', 'professional-technology', 'repository', 'kho mã nguồn', 'The repository keeps the implementation history.', '/rɪˈpɒzɪtəri/'),
  ('vocab-b2-072', 'professional-technology', 'runtime', 'môi trường chạy', 'The runtime reports an invalid setting.', '/ˈrʌntaɪm/'),
  ('vocab-b2-073', 'professional-technology', 'security', 'bảo mật', 'Security checks run before publication.', '/sɪˈkjʊərəti/'),
  ('vocab-b2-074', 'professional-technology', 'session', 'phiên làm việc', 'The session expires after inactivity.', '/ˈseʃən/'),
  ('vocab-b2-075', 'professional-technology', 'storage', 'lưu trữ', 'Private storage needs controlled access.', '/ˈstɔːrɪdʒ/'),
  ('vocab-b2-076', 'professional-technology', 'syntax', 'cú pháp', 'The compiler reports a syntax error.', '/ˈsɪntæks/'),
  ('vocab-b2-077', 'professional-technology', 'token', 'mã thông báo', 'The server validates the token.', '/ˈtəʊkən/'),
  ('vocab-b2-078', 'professional-technology', 'upload', 'tải lên', 'The editor can upload an approved document.', '/ˈʌpləʊd/'),
  ('vocab-b2-079', 'professional-technology', 'version', 'phiên bản', 'The version identifies the published content.', '/ˈvɜːʃən/'),
  ('vocab-b2-080', 'professional-technology', 'workflow', 'quy trình', 'The workflow separates draft, review, and publish.', '/ˈwɜːkfləʊ/'),
  ('vocab-b2-081', 'workplace-meetings', 'action', 'hành động cần làm', 'The minutes list each action clearly.', '/ˈækʃən/'),
  ('vocab-b2-082', 'workplace-meetings', 'assignment', 'nhiệm vụ được giao', 'The assignment has a clear owner.', '/əˈsaɪnmənt/'),
  ('vocab-b2-083', 'workplace-meetings', 'capacity', 'khả năng đáp ứng', 'The team has capacity for one more task.', '/kəˈpæsəti/'),
  ('vocab-b2-084', 'workplace-meetings', 'colleague', 'đồng nghiệp', 'My colleague will present the results.', '/ˈkɒliːɡ/'),
  ('vocab-b2-085', 'workplace-meetings', 'conflict', 'xung đột', 'The manager helped resolve the conflict.', '/ˈkɒnflɪkt/'),
  ('vocab-b2-086', 'workplace-meetings', 'contract', 'hợp đồng', 'Both sides signed the contract.', '/ˈkɒntrækt/'),
  ('vocab-b2-087', 'workplace-meetings', 'draft', 'bản nháp', 'Please review the draft before Friday.', '/drɑːft/'),
  ('vocab-b2-088', 'workplace-meetings', 'leadership', 'khả năng lãnh đạo', 'Good leadership builds trust in a team.', '/ˈliːdəʃɪp/'),
  ('vocab-b2-089', 'workplace-meetings', 'negotiate', 'đàm phán', 'We need to negotiate a fair price.', '/nɪˈɡəʊʃieɪt/'),
  ('vocab-b2-090', 'workplace-meetings', 'outcome', 'kết quả', 'The meeting produced a useful outcome.', '/ˈaʊtkʌm/'),
  ('vocab-b2-091', 'workplace-meetings', 'review', 'xem xét', 'The editor will review the new content.', '/rɪˈvjuː/'),
  ('vocab-b2-092', 'workplace-meetings', 'stakeholder', 'bên liên quan', 'Each stakeholder received the update.', '/ˈsteɪkhəʊldə/'),
  ('vocab-b2-093', 'workplace-meetings', 'strategy', 'chiến lược', 'The strategy focuses on learner retention.', '/ˈstrætədʒi/'),
  ('vocab-b2-094', 'workplace-meetings', 'target', 'mục tiêu cụ thể', 'The team reached its monthly target.', '/ˈtɑːɡɪt/'),
  ('vocab-b2-095', 'workplace-meetings', 'timeline', 'mốc thời gian', 'The timeline shows the next release steps.', '/ˈtaɪmlaɪn/'),
  ('vocab-b2-096', 'workplace-meetings', 'workload', 'khối lượng công việc', 'We shared the workload across the team.', '/ˈwɜːkləʊd/'),
  ('vocab-b2-097', 'workplace-meetings', 'deliverable', 'sản phẩm bàn giao', 'The deliverable is due at the end of the month.', '/dɪˈlɪvərəbəl/'),
  ('vocab-b2-098', 'workplace-meetings', 'observer', 'người quan sát', 'An observer joined the training session.', '/əbˈzɜːvə/'),
  ('vocab-b2-099', 'workplace-meetings', 'requirement', 'yêu cầu', 'The requirement is written in the project brief.', '/rɪˈkwaɪəmənt/'),
  ('vocab-b2-100', 'workplace-meetings', 'summary', 'bản tóm tắt', 'The summary captures the agreed next steps.', '/ˈsʌməri/')
) AS batch("id", "taxonomyNodeId", "word", "meaning", "example", "pronunciation");
