-- EP1-ST034: fourth reviewed vocabulary batch for the Phase 1 learner beta.
-- All rows are EnglishPath-authored CC0 fixtures. Rollback is owner-approved only.

INSERT INTO "GovernedVocabularyItem" ("id", "taxonomyNodeId", "word", "meaning", "example", "pronunciation", "source", "license", "reviewStatus", "reviewedAt", "publishStatus", "publishedAt", "updatedAt")
SELECT batch."id", batch."taxonomyNodeId", batch."word", batch."meaning", batch."example", NULL,
  'EnglishPath original batch 4 ' || batch."id", 'CC0-1.0', 'REVIEWED', TIMESTAMPTZ '2026-08-06T00:00:00Z',
  'PUBLISHED', TIMESTAMPTZ '2026-08-06T00:00:00Z', TIMESTAMPTZ '2026-08-06T00:00:00Z'
FROM (VALUES
  ('vocab-b4-001', 'daily-life-travel', 'beach', 'bãi biển', 'The beach is quiet early in the morning.'),
  ('vocab-b4-002', 'daily-life-travel', 'booking', 'việc đặt chỗ', 'The booking includes breakfast.'),
  ('vocab-b4-003', 'daily-life-travel', 'capital', 'thủ đô', 'We visited the capital for two days.'),
  ('vocab-b4-004', 'daily-life-travel', 'climate', 'khí hậu', 'The island has a warm climate.'),
  ('vocab-b4-005', 'daily-life-travel', 'companion', 'bạn đồng hành', 'My travel companion speaks English well.'),
  ('vocab-b4-006', 'daily-life-travel', 'discount', 'giảm giá', 'The museum offers a student discount.'),
  ('vocab-b4-007', 'daily-life-travel', 'flight', 'chuyến bay', 'Our flight leaves in the afternoon.'),
  ('vocab-b4-008', 'daily-life-travel', 'foreign', 'nước ngoài', 'She enjoys learning a foreign language.'),
  ('vocab-b4-009', 'daily-life-travel', 'guest', 'khách', 'Every guest must register at reception.'),
  ('vocab-b4-010', 'daily-life-travel', 'highway', 'đường cao tốc', 'The highway connects the two cities.'),
  ('vocab-b4-011', 'daily-life-travel', 'hotel', 'khách sạn', 'The hotel is close to the station.'),
  ('vocab-b4-012', 'daily-life-travel', 'language', 'ngôn ngữ', 'English is a useful travel language.'),
  ('vocab-b4-013', 'daily-life-travel', 'market', 'chợ', 'The morning market sells fresh fruit.'),
  ('vocab-b4-014', 'daily-life-travel', 'package', 'gói dịch vụ', 'The tour package includes transport.'),
  ('vocab-b4-015', 'daily-life-travel', 'port', 'bến cảng', 'The ferry arrived at the port.'),
  ('vocab-b4-016', 'daily-life-travel', 'public', 'công cộng', 'The city has reliable public transport.'),
  ('vocab-b4-017', 'daily-life-travel', 'region', 'vùng', 'This region is known for its coffee.'),
  ('vocab-b4-018', 'daily-life-travel', 'shelter', 'nơi trú ẩn', 'The station provides shelter from the rain.'),
  ('vocab-b4-019', 'daily-life-travel', 'shore', 'bờ biển', 'We walked along the shore.'),
  ('vocab-b4-020', 'daily-life-travel', 'traveller', 'người đi du lịch', 'The traveller asked for directions.'),
  ('vocab-b4-021', 'daily-life-travel', 'trip', 'chuyến đi', 'The school trip starts on Friday.'),
  ('vocab-b4-022', 'daily-life-travel', 'vacation', 'kỳ nghỉ', 'They plan a short vacation in July.'),
  ('vocab-b4-023', 'daily-life-travel', 'alley', 'ngõ', 'The guide led us through a narrow alley.'),
  ('vocab-b4-024', 'daily-life-travel', 'boulevard', 'đại lộ', 'The boulevard has wide sidewalks.'),
  ('vocab-b4-025', 'daily-life-travel', 'bus-stop', 'trạm xe buýt', 'The bus stop is beside the library.'),
  ('vocab-b4-026', 'daily-life-travel', 'departure-board', 'bảng giờ khởi hành', 'Check the departure board for changes.'),
  ('vocab-b4-027', 'daily-life-travel', 'fountain', 'đài phun nước', 'The children played near the fountain.'),
  ('vocab-b4-028', 'daily-life-travel', 'intersection-light', 'đèn giao thông', 'Wait for the intersection light.'),
  ('vocab-b4-029', 'daily-life-travel', 'neighbourhood', 'khu phố', 'The neighbourhood is safe at night.'),
  ('vocab-b4-030', 'daily-life-travel', 'suitcase', 'va li', 'My suitcase has a broken wheel.'),
  ('vocab-b4-031', 'professional-technology', 'alert', 'cảnh báo', 'The alert appears when a request fails.'),
  ('vocab-b4-032', 'professional-technology', 'api', 'giao diện lập trình', 'The API returns a stable envelope.'),
  ('vocab-b4-033', 'professional-technology', 'array', 'mảng dữ liệu', 'The array contains the selected items.'),
  ('vocab-b4-034', 'professional-technology', 'audit', 'kiểm toán', 'The audit records a redacted action.'),
  ('vocab-b4-035', 'professional-technology', 'authorization', 'ủy quyền', 'Authorization is checked on the server.'),
  ('vocab-b4-036', 'professional-technology', 'bearer', 'mã bearer', 'The bearer token is never shown in the UI.'),
  ('vocab-b4-037', 'professional-technology', 'controller', 'bộ điều khiển', 'The controller passes work to the service.'),
  ('vocab-b4-038', 'professional-technology', 'default', 'mặc định', 'The default page size is safe.'),
  ('vocab-b4-039', 'professional-technology', 'environment', 'môi trường', 'The environment keeps secrets outside code.'),
  ('vocab-b4-040', 'professional-technology', 'exception', 'ngoại lệ', 'The handler maps the exception safely.'),
  ('vocab-b4-041', 'professional-technology', 'frontend', 'giao diện phía trước', 'The frontend handles loading and error states.'),
  ('vocab-b4-042', 'professional-technology', 'generate', 'tạo ra', 'The command can generate a client.'),
  ('vocab-b4-043', 'professional-technology', 'guard', 'bộ bảo vệ', 'The guard rejects an unauthenticated request.'),
  ('vocab-b4-044', 'professional-technology', 'handler', 'bộ xử lý', 'The handler returns a safe error.'),
  ('vocab-b4-045', 'professional-technology', 'identity-check', 'kiểm tra danh tính', 'The identity check runs before access.'),
  ('vocab-b4-046', 'professional-technology', 'integer', 'số nguyên', 'The page number must be an integer.'),
  ('vocab-b4-047', 'professional-technology', 'json', 'dữ liệu JSON', 'The endpoint returns valid JSON.'),
  ('vocab-b4-048', 'professional-technology', 'offline', 'ngoại tuyến', 'The test uses an offline fixture.'),
  ('vocab-b4-049', 'professional-technology', 'metadata', 'siêu dữ liệu', 'The metadata contains a correlation ID.'),
  ('vocab-b4-050', 'professional-technology', 'mutation', 'thay đổi dữ liệu', 'The mutation requires an idempotency key.'),
  ('vocab-b4-051', 'professional-technology', 'nullable', 'có thể rỗng', 'The field is nullable when no value applies.'),
  ('vocab-b4-052', 'professional-technology', 'operation', 'thao tác', 'The operation completes in one transaction.'),
  ('vocab-b4-053', 'professional-technology', 'owner', 'chủ sở hữu', 'The owner can view private progress.'),
  ('vocab-b4-054', 'professional-technology', 'pagination', 'phân trang', 'Pagination keeps the response bounded.'),
  ('vocab-b4-055', 'professional-technology', 'prisma', 'Prisma', 'Prisma provides the typed database client.'),
  ('vocab-b4-056', 'professional-technology', 'protected', 'được bảo vệ', 'The protected route requires a session.'),
  ('vocab-b4-057', 'professional-technology', 'provider', 'nhà cung cấp', 'The provider remains outside the local test.'),
  ('vocab-b4-058', 'professional-technology', 'retry', 'thử lại', 'The button lets the learner retry safely.'),
  ('vocab-b4-059', 'professional-technology', 'pathway', 'lộ trình', 'The pathway stays clear and predictable.'),
  ('vocab-b4-060', 'professional-technology', 'sanitizer', 'bộ làm sạch', 'The sanitizer removes private fields.'),
  ('vocab-b4-061', 'professional-technology', 'secret', 'bí mật', 'A secret must never enter source control.'),
  ('vocab-b4-062', 'professional-technology', 'submit', 'gửi', 'The learner can submit one answer.'),
  ('vocab-b4-063', 'professional-technology', 'validator', 'bộ kiểm tra hợp lệ', 'The validator rejects unknown fields.'),
  ('vocab-b4-064', 'professional-technology', 'vault', 'kho bí mật', 'The vault protects production credentials.'),
  ('vocab-b4-065', 'professional-technology', 'adapter', 'bộ chuyển đổi', 'The adapter preserves the public contract.'),
  ('vocab-b4-066', 'professional-technology', 'assertion', 'khẳng định kiểm thử', 'The assertion checks the exact response.'),
  ('vocab-b4-067', 'professional-technology', 'boundary', 'ranh giới', 'The module defines a clear boundary.'),
  ('vocab-b4-068', 'professional-technology', 'contract-test', 'kiểm thử hợp đồng', 'The contract test checks the envelope.'),
  ('vocab-b4-069', 'professional-technology', 'dependency-graph', 'đồ thị phụ thuộc', 'The dependency graph stays acyclic.'),
  ('vocab-b4-070', 'professional-technology', 'fixture-file', 'tệp dữ liệu mẫu', 'The fixture file is deterministic.'),
  ('vocab-b4-071', 'workplace-meetings', 'account', 'tài khoản', 'The account belongs to one learner.'),
  ('vocab-b4-072', 'workplace-meetings', 'applicant', 'người nộp đơn', 'The applicant attached a clear resume.'),
  ('vocab-b4-073', 'workplace-meetings', 'attendance', 'sự tham dự', 'Attendance improved after the reminder.'),
  ('vocab-b4-074', 'workplace-meetings', 'branch', 'nhánh', 'The change is ready on a separate branch.'),
  ('vocab-b4-075', 'workplace-meetings', 'campaign', 'chiến dịch', 'The campaign has a clear target audience.'),
  ('vocab-b4-076', 'workplace-meetings', 'conference', 'hội nghị', 'She spoke at a regional conference.'),
  ('vocab-b4-077', 'workplace-meetings', 'customer', 'khách hàng', 'The customer received a quick reply.'),
  ('vocab-b4-078', 'workplace-meetings', 'corporate', 'thuộc doanh nghiệp', 'The corporate policy applies to every office.'),
  ('vocab-b4-079', 'workplace-meetings', 'cost', 'chi phí', 'The estimate includes the total cost.'),
  ('vocab-b4-080', 'workplace-meetings', 'credit', 'tín dụng', 'The shop accepts card credit.'),
  ('vocab-b4-081', 'workplace-meetings', 'delivery', 'việc giao hàng', 'The delivery arrived before lunch.'),
  ('vocab-b4-082', 'workplace-meetings', 'employee', 'nhân viên', 'Each employee receives safety training.'),
  ('vocab-b4-083', 'workplace-meetings', 'improve', 'cải thiện', 'Small changes can improve service quality.'),
  ('vocab-b4-084', 'workplace-meetings', 'industry', 'ngành công nghiệp', 'The report studies the technology industry.'),
  ('vocab-b4-085', 'workplace-meetings', 'meeting-room', 'phòng họp', 'The meeting-room is on the third floor.'),
  ('vocab-b4-086', 'workplace-meetings', 'order', 'đơn đặt hàng', 'The supplier confirmed the order.'),
  ('vocab-b4-087', 'workplace-meetings', 'partner', 'đối tác', 'Our partner shared the updated plan.'),
  ('vocab-b4-088', 'workplace-meetings', 'performance', 'hiệu suất', 'The review discusses team performance.'),
  ('vocab-b4-089', 'workplace-meetings', 'product', 'sản phẩm', 'The product solves a common problem.'),
  ('vocab-b4-090', 'workplace-meetings', 'profit', 'lợi nhuận', 'The company reinvests its profit.'),
  ('vocab-b4-091', 'workplace-meetings', 'project', 'dự án', 'The project has three milestones.'),
  ('vocab-b4-092', 'workplace-meetings', 'report', 'báo cáo', 'The report is ready for review.'),
  ('vocab-b4-093', 'workplace-meetings', 'result', 'kết quả', 'The result matched the target.'),
  ('vocab-b4-094', 'workplace-meetings', 'role', 'vai trò', 'Everyone understands their role.'),
  ('vocab-b4-095', 'workplace-meetings', 'task', 'nhiệm vụ', 'The task has a named owner.'),
  ('vocab-b4-096', 'workplace-meetings', 'team', 'đội nhóm', 'The team solved the issue together.'),
  ('vocab-b4-097', 'workplace-meetings', 'yield', 'sản lượng', 'The new method increased yield.'),
  ('vocab-b4-098', 'workplace-meetings', 'resume', 'sơ yếu lý lịch', 'The applicant updated the resume.'),
  ('vocab-b4-099', 'workplace-meetings', 'agenda-item', 'mục trong chương trình họp', 'Each agenda-item has an owner.'),
  ('vocab-b4-100', 'workplace-meetings', 'service-level', 'mức độ dịch vụ', 'The service-level target is documented.')
) AS batch("id", "taxonomyNodeId", "word", "meaning", "example");
