"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { requestLearnerApi } from "@/shared/api/learner-api-client";
import styles from "./daily-sentence.module.css";
type Envelope<T> = { data: T }; type Sentence = { localDate: string; sentence: { id: string; prompt: string } | null; completed: boolean; feedback?: { isCorrect: boolean; message: string; completedAt: string } };
export function DailySentencePage() {
  const [data, setData] = useState<Sentence | null>(null); const [answer, setAnswer] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => { requestLearnerApi<Envelope<Sentence>>("/daily-sentences/today").then(({ data: value }) => setData(value)).catch(() => setError("Chưa tải được câu học hôm nay. Hãy thử lại.")); }, []);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!data?.sentence || !answer.trim() || busy) return; setBusy(true); setError(""); try { const result = await requestLearnerApi<Envelope<Sentence>>(`/daily-sentences/${data.sentence.id}/submit`, { method: "POST", body: { answer } }); setData(result.data); } catch { setError("Chưa lưu được câu trả lời. Hãy thử lại."); } finally { setBusy(false); } }
  return <main className={styles.page}><div className={styles.shell}><header className={styles.header}><Link className={styles.brand} href="/dashboard">English<span>Path</span></Link><Link href="/dashboard" className={styles.back}>Dashboard</Link></header><section className={styles.card} aria-live="polite"><p className={styles.eyebrow}>Daily Sentence · {data?.localDate ?? "hôm nay"}</p><h1>Một câu, một bước tiến.</h1>{error && <p className={styles.error} role="alert">{error}</p>}{!data && !error && <p role="status">Đang chuẩn bị câu học...</p>}{data && !data.sentence && <p className={styles.empty}>Hôm nay chưa có câu đã được duyệt. Hãy quay lại sau.</p>}{data?.sentence && !data.completed && <form onSubmit={submit}><p className={styles.prompt}>{data.sentence.prompt}</p><label className={styles.label} htmlFor="answer">Viết lại câu tiếng Anh</label><input id="answer" value={answer} onChange={(event) => setAnswer(event.target.value)} disabled={busy} autoComplete="off" className={styles.input} /><button className={styles.button} disabled={busy || !answer.trim()}>{busy ? "Đang chấm..." : "Nộp câu trả lời"}</button></form>}{data?.completed && data.feedback && <div className={data.feedback.isCorrect ? styles.success : styles.wrong}><strong>{data.feedback.isCorrect ? "Chính xác" : "Đã ghi nhận"}</strong><p>{data.feedback.message}</p><p className={styles.muted}>Bạn đã hoàn thành Daily Sentence cho ngày này.</p></div>}</section></div></main>;
}
