-- EP1-ST033: third reviewed vocabulary batch for the Phase 1 learner beta.
-- All rows are EnglishPath-authored CC0 fixtures. Rollback is owner-approved only.

INSERT INTO "GovernedVocabularyItem" ("id", "taxonomyNodeId", "word", "meaning", "example", "pronunciation", "source", "license", "reviewStatus", "reviewedAt", "publishStatus", "publishedAt", "updatedAt")
SELECT batch."id", batch."taxonomyNodeId", batch."word", batch."meaning", batch."example", NULL,
  'EnglishPath original batch 3 ' || batch."id", 'CC0-1.0', 'REVIEWED', TIMESTAMPTZ '2026-08-06T00:00:00Z',
  'PUBLISHED', TIMESTAMPTZ '2026-08-06T00:00:00Z', TIMESTAMPTZ '2026-08-06T00:00:00Z'
FROM (VALUES
  ('vocab-b3-001', 'daily-life-travel', 'bicycle', 'xe đạp', 'I ride a bicycle to the market.'),
  ('vocab-b3-002', 'daily-life-travel', 'bridge', 'cây cầu', 'The bridge connects the two districts.'),
  ('vocab-b3-003', 'daily-life-travel', 'campsite', 'khu cắm trại', 'The campsite is near a clean lake.'),
  ('vocab-b3-004', 'daily-life-travel', 'coach', 'xe khách', 'The coach leaves at seven in the morning.'),
  ('vocab-b3-005', 'daily-life-travel', 'countryside', 'vùng nông thôn', 'We spent the weekend in the countryside.'),
  ('vocab-b3-006', 'daily-life-travel', 'crossing', 'chỗ sang đường', 'Use the pedestrian crossing here.'),
  ('vocab-b3-007', 'daily-life-travel', 'direction', 'phương hướng', 'The sign shows the direction to the station.'),
  ('vocab-b3-008', 'daily-life-travel', 'ferry', 'phà', 'The ferry crosses the river every hour.'),
  ('vocab-b3-009', 'daily-life-travel', 'festival', 'lễ hội', 'The town holds a food festival each spring.'),
  ('vocab-b3-010', 'daily-life-travel', 'inland', 'trong đất liền', 'The inland route avoids the busy coast.'),
  ('vocab-b3-011', 'daily-life-travel', 'intersection', 'ngã tư', 'Turn left at the next intersection.'),
  ('vocab-b3-012', 'daily-life-travel', 'island', 'hòn đảo', 'The island has a quiet beach.'),
  ('vocab-b3-013', 'daily-life-travel', 'kilometre', 'ki lô mét', 'The hotel is one kilometre from the port.'),
  ('vocab-b3-014', 'daily-life-travel', 'navigate', 'điều hướng', 'The map helps us navigate the old streets.'),
  ('vocab-b3-015', 'daily-life-travel', 'northern', 'phía bắc', 'The northern road is less crowded.'),
  ('vocab-b3-016', 'daily-life-travel', 'parking', 'chỗ đỗ xe', 'Parking is available behind the hotel.'),
  ('vocab-b3-017', 'daily-life-travel', 'pedestrian', 'người đi bộ', 'The driver stopped for a pedestrian.'),
  ('vocab-b3-018', 'daily-life-travel', 'picnic', 'buổi dã ngoại', 'We packed fruit for a picnic.'),
  ('vocab-b3-019', 'daily-life-travel', 'scenery', 'phong cảnh', 'The mountain scenery was beautiful.'),
  ('vocab-b3-020', 'daily-life-travel', 'subway', 'tàu điện ngầm', 'The subway is the fastest way downtown.'),
  ('vocab-b3-021', 'daily-life-travel', 'sunrise', 'bình minh', 'We watched the sunrise from the hill.'),
  ('vocab-b3-022', 'daily-life-travel', 'tram', 'xe điện', 'The tram stops outside the museum.'),
  ('vocab-b3-023', 'daily-life-travel', 'tunnel', 'đường hầm', 'The train entered a long tunnel.'),
  ('vocab-b3-024', 'daily-life-travel', 'umbrella', 'ô dù', 'Take an umbrella because rain is likely.'),
  ('vocab-b3-025', 'daily-life-travel', 'visitor', 'khách tham quan', 'Every visitor receives a simple map.'),
  ('vocab-b3-026', 'daily-life-travel', 'walking', 'đi bộ', 'Walking is a good way to see the city.'),
  ('vocab-b3-027', 'daily-life-travel', 'waterfall', 'thác nước', 'The trail ends at a small waterfall.'),
  ('vocab-b3-028', 'daily-life-travel', 'weather', 'thời tiết', 'The weather changed during the trip.'),
  ('vocab-b3-029', 'daily-life-travel', 'western', 'phía tây', 'The western gate closes at sunset.'),
  ('vocab-b3-030', 'daily-life-travel', 'compass', 'la bàn', 'A compass can help on a forest walk.'),
  ('vocab-b3-031', 'daily-life-travel', 'detour', 'đường vòng', 'Road work forced us to take a detour.'),
  ('vocab-b3-032', 'daily-life-travel', 'harbour', 'bến cảng', 'Fishing boats returned to the harbour.'),
  ('vocab-b3-033', 'daily-life-travel', 'inquiry', 'câu hỏi tìm hiểu', 'The visitor made an inquiry at the desk.'),
  ('vocab-b3-034', 'daily-life-travel', 'mainland', 'đất liền', 'The boat returns to the mainland at noon.'),
  ('vocab-b3-035', 'daily-life-travel', 'reservation-code', 'mã đặt chỗ', 'Write the reservation code on the form.'),
  ('vocab-b3-036', 'professional-technology', 'analytics', 'phân tích dữ liệu', 'Analytics show which lessons need review.'),
  ('vocab-b3-037', 'professional-technology', 'attribute', 'thuộc tính', 'The record has an attribute for its owner.'),
  ('vocab-b3-038', 'professional-technology', 'build', 'bản dựng', 'The build completed without warnings.'),
  ('vocab-b3-039', 'professional-technology', 'callback', 'hàm gọi lại', 'The callback runs after the request finishes.'),
  ('vocab-b3-040', 'professional-technology', 'class', 'lớp', 'The class groups related behavior.'),
  ('vocab-b3-041', 'professional-technology', 'code', 'mã nguồn', 'Review the code before merging it.'),
  ('vocab-b3-042', 'professional-technology', 'dependency', 'phụ thuộc', 'The module has one external dependency.'),
  ('vocab-b3-043', 'professional-technology', 'deployment', 'triển khai hệ thống', 'The deployment uses a clean environment.'),
  ('vocab-b3-044', 'professional-technology', 'design', 'thiết kế', 'The design keeps the main action visible.'),
  ('vocab-b3-045', 'professional-technology', 'developer', 'nhà phát triển', 'The developer added a focused test.'),
  ('vocab-b3-046', 'professional-technology', 'envelope', 'vỏ phản hồi', 'The response envelope includes safe metadata.'),
  ('vocab-b3-047', 'professional-technology', 'event', 'sự kiện', 'The server records a redacted event.'),
  ('vocab-b3-048', 'professional-technology', 'fixture', 'dữ liệu mẫu', 'The test uses a deterministic fixture.'),
  ('vocab-b3-049', 'professional-technology', 'gateway', 'cổng kết nối', 'The gateway validates the incoming request.'),
  ('vocab-b3-050', 'professional-technology', 'identity', 'danh tính', 'The service maps the external identity safely.'),
  ('vocab-b3-051', 'professional-technology', 'latency', 'độ trễ', 'Lower latency makes the lesson feel faster.'),
  ('vocab-b3-052', 'professional-technology', 'migration', 'bản di chuyển dữ liệu', 'The migration adds only new rows.'),
  ('vocab-b3-053', 'professional-technology', 'object', 'đối tượng', 'The object contains the validated values.'),
  ('vocab-b3-054', 'professional-technology', 'parameter', 'tham số', 'The parameter limits the page size.'),
  ('vocab-b3-055', 'professional-technology', 'pipeline', 'quy trình xử lý', 'The pipeline checks rights before import.'),
  ('vocab-b3-056', 'professional-technology', 'policy', 'chính sách', 'The policy denies an unknown role.'),
  ('vocab-b3-057', 'professional-technology', 'production', 'môi trường sản xuất', 'Production credentials stay outside tests.'),
  ('vocab-b3-058', 'professional-technology', 'queue', 'hàng đợi', 'The queue keeps review tasks in order.'),
  ('vocab-b3-059', 'professional-technology', 'response', 'phản hồi', 'The response contains the requested page.'),
  ('vocab-b3-060', 'professional-technology', 'schema', 'lược đồ', 'The schema defines each required field.'),
  ('vocab-b3-061', 'professional-technology', 'service', 'dịch vụ', 'The service owns the business rule.'),
  ('vocab-b3-062', 'professional-technology', 'source', 'nguồn', 'The source is recorded for governance.'),
  ('vocab-b3-063', 'professional-technology', 'state', 'trạng thái', 'The state comes from the server.'),
  ('vocab-b3-064', 'professional-technology', 'string', 'chuỗi ký tự', 'The field accepts a bounded string.'),
  ('vocab-b3-065', 'professional-technology', 'system', 'hệ thống', 'The system protects learner ownership.'),
  ('vocab-b3-066', 'professional-technology', 'testing', 'kiểm thử', 'Testing catches regressions before release.'),
  ('vocab-b3-067', 'professional-technology', 'timeout', 'thời gian chờ', 'The client shows a retry after a timeout.'),
  ('vocab-b3-068', 'professional-technology', 'trace', 'dấu vết truy vết', 'The trace links related service events.'),
  ('vocab-b3-069', 'professional-technology', 'transaction', 'giao dịch', 'The transaction prevents a partial write.'),
  ('vocab-b3-070', 'professional-technology', 'type', 'kiểu dữ liệu', 'The type prevents an invalid value.'),
  ('vocab-b3-071', 'professional-technology', 'unit', 'đơn vị kiểm thử', 'The unit test isolates one rule.'),
  ('vocab-b3-072', 'professional-technology', 'variable', 'biến', 'The variable stores the current page.'),
  ('vocab-b3-073', 'professional-technology', 'webhook', 'liên kết gọi lại', 'The webhook sends a bounded event.'),
  ('vocab-b3-074', 'professional-technology', 'whitelist', 'danh sách cho phép', 'The whitelist limits accepted fields.'),
  ('vocab-b3-075', 'professional-technology', 'consumer', 'bên sử dụng', 'The consumer reads the public projection.'),
  ('vocab-b3-076', 'workplace-meetings', 'acquire', 'có được', 'The team needs to acquire new skills.'),
  ('vocab-b3-077', 'workplace-meetings', 'annual', 'hàng năm', 'The annual review starts in June.'),
  ('vocab-b3-078', 'workplace-meetings', 'benefit', 'phúc lợi', 'Health insurance is an important benefit.'),
  ('vocab-b3-079', 'workplace-meetings', 'bonus', 'tiền thưởng', 'The team received a performance bonus.'),
  ('vocab-b3-080', 'workplace-meetings', 'budget', 'ngân sách', 'The project budget covers the first release.'),
  ('vocab-b3-081', 'workplace-meetings', 'candidate', 'ứng viên', 'The candidate answered clearly.'),
  ('vocab-b3-082', 'workplace-meetings', 'career', 'sự nghiệp', 'The course supports her career goals.'),
  ('vocab-b3-083', 'workplace-meetings', 'department', 'phòng ban', 'The finance department sent the report.'),
  ('vocab-b3-084', 'workplace-meetings', 'employer', 'người sử dụng lao động', 'The employer offers flexible hours.'),
  ('vocab-b3-085', 'workplace-meetings', 'employment', 'việc làm', 'The form asks about previous employment.'),
  ('vocab-b3-086', 'workplace-meetings', 'estimate', 'ước tính', 'The estimate includes labour and materials.'),
  ('vocab-b3-087', 'workplace-meetings', 'expense', 'chi phí', 'Submit each expense with a receipt.'),
  ('vocab-b3-088', 'workplace-meetings', 'income', 'thu nhập', 'The survey does not store private income data.'),
  ('vocab-b3-089', 'workplace-meetings', 'interview', 'phỏng vấn', 'The interview begins at nine.'),
  ('vocab-b3-090', 'workplace-meetings', 'invoice', 'hóa đơn', 'The supplier sent an invoice by email.'),
  ('vocab-b3-091', 'workplace-meetings', 'manager', 'quản lý', 'The manager approved the training plan.'),
  ('vocab-b3-092', 'workplace-meetings', 'overtime', 'làm thêm giờ', 'The team avoided unnecessary overtime.'),
  ('vocab-b3-093', 'workplace-meetings', 'payment', 'khoản thanh toán', 'The payment arrived on Monday.'),
  ('vocab-b3-094', 'workplace-meetings', 'salary', 'lương', 'The offer includes a monthly salary.'),
  ('vocab-b3-095', 'workplace-meetings', 'supplier', 'nhà cung cấp', 'The supplier confirmed the delivery date.'),
  ('vocab-b3-096', 'workplace-meetings', 'training', 'đào tạo', 'New staff complete safety training.'),
  ('vocab-b3-097', 'workplace-meetings', 'vacancy', 'vị trí tuyển dụng', 'The company posted a vacancy online.'),
  ('vocab-b3-098', 'workplace-meetings', 'workplace', 'nơi làm việc', 'A respectful workplace helps people learn.'),
  ('vocab-b3-099', 'workplace-meetings', 'commute', 'đi lại hàng ngày', 'My commute takes about twenty minutes.'),
  ('vocab-b3-100', 'workplace-meetings', 'promotion', 'thăng chức', 'She earned a promotion after leading the project.')
) AS batch("id", "taxonomyNodeId", "word", "meaning", "example");
