"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { formatRemaining, type TimedMode, type TimedSession } from "@/entities/toeic-timed-test/model/contracts";
import { answerTimedTest, getTimedTest, resultTimedTest, startTimedTest, submitTimedTest } from "@/features/toeic-timed-test/api/timed-test-api";
import { clearActiveSessionId, readActiveSessionId, readClientSessionId, writeActiveSessionId } from "@/features/toeic-timed-test/model/client-session";
import styles from "./toeic-timed-test-page.module.css";

export function ToeicTimedTestPage() {
  const [mode, setMode] = useState<TimedMode>("MINI"); const [session, setSession] = useState<TimedSession | null>(null); const [selected, setSelected] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [remaining, setRemaining] = useState(0);
  const current = session?.status === "ACTIVE" ? session.questions[session.answered] : undefined;
  const reconcile = async (id: string) => { try { const value = await resultTimedTest(id); setSession(value); setRemaining(value.remainingSeconds); if (value.status !== "ACTIVE") clearActiveSessionId(); } catch { setError("Chưa tải được trạng thái bài thi. Hãy thử lại."); } };
  useEffect(() => { const id = readActiveSessionId(); if (!id) return; void getTimedTest(id).then((value) => { setSession(value); setRemaining(value.remainingSeconds); }).catch(() => clearActiveSessionId()); }, []);
  useEffect(() => { // eslint-disable-next-line react-hooks/set-state-in-effect
    setRemaining(session?.remainingSeconds ?? 0); if (!session || session.status !== "ACTIVE") return; const timer = window.setInterval(() => setRemaining((value) => { if (value <= 1) { window.clearInterval(timer); void reconcile(session.sessionId); return 0; } return value - 1; }), 1000); return () => window.clearInterval(timer); }, [session]);
  async function start() { if (busy) return; setBusy(true); setError(""); try { const value = await startTimedTest(readClientSessionId(), mode); setSession(value); setRemaining(value.remainingSeconds); writeActiveSessionId(value.sessionId); } catch { setError("Chưa mở được bài thi. Hãy kiểm tra kết nối và thử lại."); } finally { setBusy(false); } }
  async function answer() { if (!session || !current || !selected || busy || remaining <= 0) return; setBusy(true); setError(""); try { const ack = await answerTimedTest(session.sessionId, current.id, selected); setSession({ ...session, answered: ack.answered }); setSelected(""); } catch { setError("Chưa ghi nhận được câu trả lời. Bạn vẫn ở câu này; hãy thử lại."); } finally { setBusy(false); } }
  async function submit() { if (!session || busy) return; setBusy(true); setError(""); try { const value = await submitTimedTest(session.sessionId); setSession(value); setRemaining(value.remainingSeconds); if (value.status !== "ACTIVE") clearActiveSessionId(); } catch { setError("Chưa tải được kết quả. Hãy thử lại; tiến độ vẫn được giữ."); } finally { setBusy(false); } }
  return <main className={styles.page}><div className={styles.shell}><Link href="/toeic/practice" className={styles.back}>Về TOEIC Practice</Link><p className={styles.kicker}>TOEIC timed test</p><h1>Thi thử theo nhịp của bạn</h1><p className={styles.lede}>Thời lượng và số câu do máy chủ quyết định. Bạn có thể quay lại sau khi làm gián đoạn.</p>{error && <p className={styles.error} aria-live="polite">{error}</p>}
    {!session && <section className={styles.panel} aria-labelledby="setup"><h2 id="setup">Chọn bài thi</h2><div className={styles.modes}>{(["MINI", "HALF"] as TimedMode[]).map((value) => <button key={value} type="button" className={mode === value ? styles.active : styles.secondary} onClick={() => setMode(value)} aria-pressed={mode === value}><strong>{value}</strong><span>{value === "MINI" ? "20 câu · 20 phút" : "50 câu · 45 phút"}</span></button>)}</div><button className={styles.primary} type="button" disabled={busy} onClick={() => void start()}>{busy ? "Đang mở bài…" : "Bắt đầu bài thi"}</button></section>}
    {session?.status === "ACTIVE" && current && <><section className={styles.panel}><div className={styles.progress}>Câu {session.answered + 1} / {session.total}<span aria-label={`Còn ${formatRemaining(remaining)}`}>Còn {formatRemaining(remaining)}</span></div><p className={styles.progressText}>{session.answered} câu đã được máy chủ ghi nhận.</p><h2>{current.prompt}</h2></section><section className={styles.options} aria-label="Các lựa chọn">{current.options.map((option) => <button key={option.id} type="button" className={selected === option.id ? styles.optionSelected : styles.option} aria-pressed={selected === option.id} disabled={busy || remaining <= 0} onClick={() => setSelected(option.id)}><b>{option.id}</b><span>{option.text}</span></button>)}<button className={styles.primary} type="button" disabled={!selected || busy || remaining <= 0} onClick={() => void answer()}>{busy ? "Đang ghi nhận…" : session.answered + 1 === session.total ? "Ghi nhận câu cuối" : "Ghi nhận và tiếp tục"}</button></section></>}
    {session?.status === "ACTIVE" && !current && <section className={styles.panel}><h2>Sẵn sàng nộp bài</h2><p>Máy chủ đã ghi nhận đủ câu trả lời.</p><button className={styles.primary} disabled={busy} onClick={() => void submit()}>{busy ? "Đang nộp…" : "Nộp bài"}</button></section>}
    {session && session.status !== "ACTIVE" && <section className={styles.panel} aria-live="polite"><p className={styles.kicker}>{session.status === "EXPIRED" ? "Hết giờ" : "Đã hoàn thành"}</p><h2>Kết quả an toàn</h2><p>{session.mode} · {session.answered}/{session.total} câu đã ghi nhận{typeof session.score === "number" ? ` · Điểm: ${session.score}` : ""}</p><button className={styles.secondary} onClick={() => { setSession(null); setError(""); }}>Làm bài mới</button></section>}
  </div></main>;
}
