import type { Article } from "./articles";

export const additionalArticles: readonly Article[] = [
  {
    title: "Cách dùng do và make để nói tự nhiên hơn",
    slug: "cach-dung-do-va-make",
    seoTitle: "Phân biệt do và make bằng ví dụ tiếng Anh dễ nhớ",
    metaDescription: "Nắm cách phân biệt do và make qua những tình huống thường gặp trong học tập, công việc và đời sống.",
    excerpt: "Một quy tắc ngắn gọn giúp bạn chọn do hay make tự tin hơn khi nói và viết.",
    category: "Grammar Guide",
    tags: ["Từ dễ nhầm", "Ngữ pháp", "A2-B1"],
    publishedAt: "2026-07-03",
    updatedAt: "2026-07-03",
    readingMinutes: 6,
    sections: [
      { heading: "Do cho hoạt động và nhiệm vụ", paragraphs: ["Dùng do khi nói về công việc, nhiệm vụ hoặc hoạt động chưa nhấn vào sản phẩm cụ thể.", "Hãy ghép do với những cụm gần cuộc sống của bạn để ghi nhớ theo ngữ cảnh."] },
      { heading: "Make cho kết quả và sản phẩm", paragraphs: ["Make thường đi với thứ được tạo ra hoặc kết quả của một quyết định.", "Bạn có thể luyện bằng cách viết ba câu về một ngày làm việc của mình."] },
    ],
    faq: [{ question: "Make a mistake hay do a mistake?", answer: "Cụm đúng là make a mistake vì mistake là kết quả của hành động." }],
    relatedSlugs: ["say-tell-speak-talk-khac-nhau", "7-cum-tieng-anh-giao-tiep-tu-nhien"],
  },
  {
    title: "5 cách nói lịch sự khi cần nhờ giúp đỡ",
    slug: "cach-nho-giup-do-lich-su-bang-tieng-anh",
    seoTitle: "5 cách nhờ giúp đỡ lịch sự bằng tiếng Anh",
    metaDescription: "Học các mẫu câu nhờ giúp đỡ bằng tiếng Anh theo mức độ thân mật, lịch sự và chuyên nghiệp.",
    excerpt: "Biết mở lời đúng cách giúp yêu cầu của bạn rõ ràng mà vẫn giữ được thiện cảm.",
    category: "Daily English",
    tags: ["Giao tiếp", "Công việc", "A2-B1"],
    publishedAt: "2026-07-01",
    updatedAt: "2026-07-01",
    readingMinutes: 5,
    sections: [
      { heading: "Bắt đầu bằng một lời mở nhẹ", paragraphs: ["Could you help me...? phù hợp trong nhiều tình huống và không quá cứng.", "Khi nói với đồng nghiệp, hãy nêu việc cần hỗ trợ và thời hạn để người nghe dễ trả lời."] },
      { heading: "Thêm lý do ngắn gọn", paragraphs: ["Một lý do cụ thể làm yêu cầu trở nên hợp tác hơn thay vì chỉ là mệnh lệnh.", "Bạn không cần giải thích dài; một câu đủ rõ là tốt nhất."] },
    ],
    faq: [{ question: "Can you help me có lịch sự không?", answer: "Có. Với bối cảnh trang trọng hơn, bạn có thể dùng Could you help me...? hoặc Would you mind...?" }],
    relatedSlugs: ["7-cum-tieng-anh-giao-tiep-tu-nhien", "lo-trinh-10-phut-hoc-tieng-anh"],
  },
  {
    title: "Cách luyện nghe tiếng Anh bằng một đoạn hội thoại ngắn",
    slug: "luyen-nghe-tieng-anh-bang-hoi-thoai-ngan",
    seoTitle: "Cách luyện nghe tiếng Anh với hội thoại ngắn mỗi ngày",
    metaDescription: "Quy trình bốn lượt nghe giúp người học tiếng Anh bắt âm, hiểu ý và nói lại một đoạn hội thoại ngắn.",
    excerpt: "Không cần nghe thật nhiều: hãy nghe một đoạn đủ ngắn theo đúng bốn lượt có mục đích.",
    category: "Listening",
    tags: ["Nghe", "Thói quen", "A2-B1"],
    publishedAt: "2026-06-29",
    updatedAt: "2026-06-29",
    readingMinutes: 7,
    sections: [
      { heading: "Lượt một: nghe ý chính", paragraphs: ["Đừng dừng lại ở từng từ. Hãy đoán người nói đang ở đâu và muốn làm gì."] },
      { heading: "Lượt hai và ba: bắt âm, rồi kiểm tra", paragraphs: ["Ghi lại từ bạn nghe được trước khi xem transcript.", "Sau đó đánh dấu âm nối hoặc từ yếu khiến bạn nghe nhầm."] },
      { heading: "Lượt bốn: nói lại", paragraphs: ["Bắt chước nhịp và ngữ điệu trong một câu, rồi thay một chi tiết bằng thông tin của bạn."] },
    ],
    faq: [{ question: "Nên nghe bao nhiêu lần?", answer: "Bốn lượt có mục đích thường hiệu quả hơn việc bật đi bật lại không có nhiệm vụ." }],
    relatedSlugs: ["lo-trinh-10-phut-hoc-tieng-anh", "7-cum-tieng-anh-giao-tiep-tu-nhien"],
  },
  {
    title: "Mẹo nhớ từ vựng theo câu chuyện thay vì danh sách",
    slug: "nho-tu-vung-theo-cau-chuyen",
    seoTitle: "Mẹo nhớ từ vựng tiếng Anh theo câu chuyện",
    metaDescription: "Biến nhóm từ vựng thành một câu chuyện ngắn để tạo liên kết và ôn lại chủ động hơn.",
    excerpt: "Một câu chuyện có ngữ cảnh giúp từ mới có chỗ đứng trong trí nhớ lâu hơn.",
    category: "Vocabulary",
    tags: ["Từ vựng", "SRS", "A2-B1"],
    publishedAt: "2026-06-27",
    updatedAt: "2026-06-27",
    readingMinutes: 5,
    sections: [
      { heading: "Chọn một nhóm nhỏ", paragraphs: ["Chọn năm từ có liên quan thay vì chép một danh sách dài.", "Ưu tiên từ bạn có thể gặp trong lịch học, công việc hoặc sở thích."] },
      { heading: "Viết câu chuyện có chi tiết thật", paragraphs: ["Một địa điểm, thời gian hoặc người quen sẽ làm câu chuyện dễ gọi lại hơn.", "Sau đó che từ tiếng Anh và tự nhớ lại trước khi xem đáp án."] },
    ],
    faq: [{ question: "Một lần nên học bao nhiêu từ?", answer: "Năm đến mười từ có ví dụ và lượt ôn lại thường dễ duy trì hơn số lượng lớn." }],
    relatedSlugs: ["lo-trinh-10-phut-hoc-tieng-anh", "luyen-nghe-tieng-anh-bang-hoi-thoai-ngan"],
  },
  {
    title: "Present perfect: khi nào dùng have hoặc has?",
    slug: "present-perfect-have-has",
    seoTitle: "Present perfect: cách dùng have và has dễ hiểu",
    metaDescription: "Hiểu present perfect qua mối liên hệ giữa quá khứ và hiện tại, kèm ví dụ ngắn cho người học Việt.",
    excerpt: "Tập trung vào ý nghĩa kết nối với hiện tại thay vì học thuộc một danh sách tín hiệu.",
    category: "Grammar Guide",
    tags: ["Ngữ pháp", "Present perfect", "B1"],
    publishedAt: "2026-06-25",
    updatedAt: "2026-06-25",
    readingMinutes: 7,
    sections: [
      { heading: "Kết quả còn liên quan hiện tại", paragraphs: ["Dùng have hoặc has cùng past participle khi hành động đã xảy ra nhưng kết quả vẫn quan trọng lúc nói."] },
      { heading: "Kinh nghiệm và khoảng thời gian chưa kết thúc", paragraphs: ["Các từ như ever, never, this week thường đi với trải nghiệm hoặc khoảng thời gian vẫn còn mở.", "Hãy tự viết một câu thật về tuần này để kiểm tra cách dùng."] },
    ],
    faq: [{ question: "Có dùng present perfect với yesterday không?", answer: "Thông thường không. Yesterday là thời điểm đã kết thúc nên past simple phù hợp hơn." }],
    relatedSlugs: ["say-tell-speak-talk-khac-nhau", "cach-dung-do-va-make"],
  },
  {
    title: "Cách đặt mục tiêu TOEIC thực tế trong 30 ngày",
    slug: "dat-muc-tieu-toeic-trong-30-ngay",
    seoTitle: "Cách đặt mục tiêu TOEIC thực tế trong 30 ngày",
    metaDescription: "Lập mục tiêu TOEIC 30 ngày bằng đầu vào hiện tại, thời gian học và các chỉ số có thể kiểm tra mỗi tuần.",
    excerpt: "Một mục tiêu tốt phải gắn với thời gian học thật và dấu hiệu tiến bộ quan sát được.",
    category: "TOEIC",
    tags: ["TOEIC", "Mục tiêu", "Tự học"],
    publishedAt: "2026-06-23",
    updatedAt: "2026-06-23",
    readingMinutes: 6,
    sections: [
      { heading: "Đo điểm xuất phát", paragraphs: ["Làm một bài kiểm tra ngắn trong điều kiện ổn định và ghi lại lỗi theo kỹ năng."] },
      { heading: "Chia mục tiêu thành tuần", paragraphs: ["Mỗi tuần chọn một trọng tâm, một lượng bài vừa sức và một lần tự kiểm tra.", "Đừng đổi kế hoạch mỗi ngày chỉ vì một buổi học không tốt."] },
    ],
    faq: [{ question: "30 ngày có đủ để tăng điểm không?", answer: "Mức tăng phụ thuộc điểm xuất phát và thời lượng học; 30 ngày phù hợp để tạo dữ liệu và thói quen đo tiến bộ." }],
    relatedSlugs: ["lo-trinh-10-phut-hoc-tieng-anh", "luyen-nghe-tieng-anh-bang-hoi-thoai-ngan"],
  },
  {
    title: "Checklist tự sửa một đoạn viết tiếng Anh ngắn",
    slug: "checklist-tu-sua-doan-viet-tieng-anh",
    seoTitle: "Checklist tự sửa đoạn viết tiếng Anh ngắn",
    metaDescription: "Bốn lượt kiểm tra giúp người học tự sửa ý, động từ, liên kết và lỗi chính tả trong đoạn viết tiếng Anh.",
    excerpt: "Sửa theo thứ tự giúp bạn nhìn ra lỗi quan trọng trước khi sa vào việc thay từng từ.",
    category: "Writing",
    tags: ["Viết", "Tự học", "A2-B1"],
    publishedAt: "2026-06-21",
    updatedAt: "2026-06-21",
    readingMinutes: 5,
    sections: [
      { heading: "Kiểm tra ý và câu chủ đề", paragraphs: ["Đọc một lượt chỉ để xem đoạn viết có trả lời đúng câu hỏi và mỗi câu có vai trò rõ không."] },
      { heading: "Kiểm tra động từ và liên kết", paragraphs: ["Gạch chân động từ, chủ ngữ và từ nối. Đây thường là nơi tạo ra lỗi ảnh hưởng lớn nhất đến độ rõ."] },
      { heading: "Đọc thành tiếng lần cuối", paragraphs: ["Đọc chậm để phát hiện câu quá dài, từ lặp và chỗ cần ngắt ý."] },
    ],
    faq: [{ question: "Nên sửa ngữ pháp hay ý trước?", answer: "Sửa ý và cấu trúc trước, rồi mới sửa ngữ pháp và chính tả để không tối ưu một câu không cần thiết." }],
    relatedSlugs: ["cach-nho-giup-do-lich-su-bang-tieng-anh", "lo-trinh-10-phut-hoc-tieng-anh"],
  },
];
