export const guestGoals = [
  {
    id: "foundation",
    label: "Xây nền tiếng Anh",
    duration: "120 ngày",
    focus: "Từ vựng nền tảng và mẫu câu thiết yếu",
    vocabulary: "steady · đều đặn",
    quiz: "Chọn câu đúng: I study English every day.",
    sentence: "I am building a strong foundation.",
  },
  {
    id: "communication",
    label: "Giao tiếp hằng ngày",
    duration: "60 ngày",
    focus: "Phản xạ trong tình huống quen thuộc",
    vocabulary: "catch up · trò chuyện, cập nhật",
    quiz: "Chọn lời đáp tự nhiên cho: How have you been?",
    sentence: "Could you say that one more time?",
  },
  {
    id: "four-skills",
    label: "Tiếng Anh bốn kỹ năng",
    duration: "90 ngày",
    focus: "Nghe, nói, đọc và viết cân bằng",
    vocabulary: "summarize · tóm tắt",
    quiz: "Nghe ý chính rồi chọn bản tóm tắt phù hợp.",
    sentence: "Let me summarize the main idea.",
  },
  {
    id: "workplace",
    label: "Tiếng Anh công việc",
    duration: "60 ngày",
    focus: "Email, họp và trao đổi chuyên nghiệp",
    vocabulary: "deadline · thời hạn",
    quiz: "Chọn câu nhắc deadline lịch sự nhất.",
    sentence: "Could we confirm the deadline today?",
  },
  {
    id: "toeic-lr",
    label: "TOEIC Listening & Reading",
    duration: "90 ngày",
    focus: "Từ vựng TOEIC và chiến lược Part 1–7",
    vocabulary: "shipment · lô hàng",
    quiz: "Part 5: The order ___ tomorrow.",
    sentence: "The shipment is scheduled to arrive tomorrow.",
  },
  {
    id: "toeic-sw",
    label: "TOEIC Speaking & Writing",
    duration: "90 ngày",
    focus: "Phản hồi nói và viết theo tình huống công việc",
    vocabulary: "proposal · đề xuất",
    quiz: "Chọn câu mở đầu phù hợp cho một đề xuất.",
    sentence: "I would like to propose a practical solution.",
  },
  {
    id: "toeic-four-skills",
    label: "TOEIC bốn kỹ năng",
    duration: "120 ngày",
    focus: "Lộ trình tích hợp Listening, Reading, Speaking, Writing",
    vocabulary: "coordinate · phối hợp",
    quiz: "Đọc thông báo rồi ghi âm một phản hồi ngắn.",
    sentence: "I will coordinate with the team this afternoon.",
  },
] as const;

export type GuestGoalId = (typeof guestGoals)[number]["id"];
