export const EXTERNAL_IDENTITY_VERIFIER = Symbol('EXTERNAL_IDENTITY_VERIFIER');
export const APPLICATION_PRINCIPAL_RESOLVER = Symbol(
  'APPLICATION_PRINCIPAL_RESOLVER',
);
export const APPLICATION_IDENTITY_REPOSITORY = Symbol(
  'APPLICATION_IDENTITY_REPOSITORY',
);
export const APPLICATION_ROLE_REPOSITORY = Symbol(
  'APPLICATION_ROLE_REPOSITORY',
);
export const OWNED_PROFILE_REPOSITORY = Symbol('OWNED_PROFILE_REPOSITORY');
